chore: add deprecation message to readme
wildlink/wildlink-js-client pull request #85
Opened 2024-05-02 17:22 UTC by Innectic

Add a deprecation message to the readme

2024-05-02 17:23 UTC, kylekurz requested changes
Should probably bump the version with this right?

2024-05-02 17:52 UTC, kylekurz approved these changes

2024-05-06 15:13 UTC, jojobii-arks approved these changes

2024-05-06 15:13 UTC, AlfredoMoralesWF approved these changes

2024-05-06 15:14 UTC, merged